//! river virtual global interface
//!
//! This global interface should only be advertised to the client if the
//! river_window_manager_v1 global is also advertised.

use crate::protocol_helpers::prelude::*;
use super::super::all_types::*;

/// A river_virtual_keyboard_manager_v1 object.
///
/// See the documentation of [the module][self] for the interface description.
pub struct RiverVirtualKeyboardManagerV1 {
    core: ObjectCore,
    handler: HandlerHolder<dyn RiverVirtualKeyboardManagerV1Handler>,
}

struct DefaultHandler;

impl RiverVirtualKeyboardManagerV1Handler for DefaultHandler { }

impl ConcreteObject for RiverVirtualKeyboardManagerV1 {
    const XML_VERSION: u32 = 1;
    const INTERFACE: ObjectInterface = ObjectInterface::RiverVirtualKeyboardManagerV1;
    const INTERFACE_NAME: &str = "river_virtual_keyboard_manager_v1";
}

impl RiverVirtualKeyboardManagerV1 {
    /// Sets a new handler.
    pub fn set_handler(&self, handler: impl RiverVirtualKeyboardManagerV1Handler) {
        self.set_boxed_handler(Box::new(handler));
    }

    /// Sets a new, already boxed handler.
    pub fn set_boxed_handler(&self, handler: Box<dyn RiverVirtualKeyboardManagerV1Handler>) {
        if self.core.state.destroyed.get() {
            return;
        }
        self.handler.set(Some(handler));
    }
}

impl Debug for RiverVirtualKeyboardManagerV1 {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RiverVirtualKeyboardManagerV1")
            .field("server_obj_id", &self.core.server_obj_id.get())
            .field("client_id", &self.core.client_id.get())
            .field("client_obj_id", &self.core.client_obj_id.get())
            .finish()
    }
}

impl RiverVirtualKeyboardManagerV1 {
    /// Since when the destroy message is available.
    pub const MSG__DESTROY__SINCE: u32 = 1;

    /// destroy the river_virtual_keyboard_v1 object
    ///
    /// This request indicates that the client will no longer use the
    /// river_virtual_keyboard_v1 object.
    #[inline]
    pub fn try_send_destroy(
        &self,
    ) -> Result<(), ObjectError> {
        let core = self.core();
        let Some(id) = core.server_obj_id.get() else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoServerId));
        };
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, id: u32) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      <= river_virtual_keyboard_manager_v1#{}.destroy()\n", id);
                state.log(args);
            }
            log(&self.core.state, id);
        }
        let Some(endpoint) = &self.core.state.server else {
            return Ok(());
        };
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, None);
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            0,
        ]);
        self.core.handle_server_destroy();
        Ok(())
    }

    /// destroy the river_virtual_keyboard_v1 object
    ///
    /// This request indicates that the client will no longer use the
    /// river_virtual_keyboard_v1 object.
    #[inline]
    pub fn send_destroy(
        &self,
    ) {
        let res = self.try_send_destroy(
        );
        if let Err(e) = res {
            log_send("river_virtual_keyboard_manager_v1.destroy", &e);
        }
    }

    /// Since when the sync_keyboard message is available.
    pub const MSG__SYNC_KEYBOARD__SINCE: u32 = 1;

    /// sync a virtual keyboard with the manage sequence
    ///
    /// Mark a zwp_virtual_keyboard_v1 as synchronized with the
    /// river_window_manager_v1 manage sequence.
    ///
    /// Virtual keyboard events generated by the zwp_virtual_keyboard_v1.key and
    /// zwp_virtual_keyboard_v1.modifiers requests on the given virtual keyboard
    /// are queued and sent to the client with keyboard focus in a batch at the
    /// end of each manage sequence.
    ///
    /// Note that the capacity of the compositor's event queue is necessarily
    /// finite, though the compositor should choose large enough limits to allow
    /// any "reasonable" usage of this protocol.
    ///
    /// This request must be made before the first
    /// zwp_virtual_keyboard_v1.keymap request for the given virtual keyboard.
    ///
    /// This request only has an effect if the client is the active river window
    /// manager.
    ///
    /// This request is idempotent, subsequent requests for the same
    /// zwp_virtual_keyboard_v1 object have no effect.
    ///
    /// # Arguments
    ///
    /// - `virtual_keyboard`: virtual keyboard to sync
    #[inline]
    pub fn try_send_sync_keyboard(
        &self,
        virtual_keyboard: &Rc<ZwpVirtualKeyboardV1>,
    ) -> Result<(), ObjectError> {
        let (
            arg0,
        ) = (
            virtual_keyboard,
        );
        let arg0 = arg0.core();
        let core = self.core();
        let Some(id) = core.server_obj_id.get() else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoServerId));
        };
        let arg0_id = match arg0.server_obj_id.get() {
            None => return Err(ObjectError(ObjectErrorKind::ArgNoServerId("virtual_keyboard"))),
            Some(id) => id,
        };
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, id: u32, arg0: u32) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      <= river_virtual_keyboard_manager_v1#{}.sync_keyboard(virtual_keyboard: zwp_virtual_keyboard_v1#{})\n", id, arg0);
                state.log(args);
            }
            log(&self.core.state, id, arg0_id);
        }
        let Some(endpoint) = &self.core.state.server else {
            return Ok(());
        };
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, None);
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            1,
            arg0_id,
        ]);
        Ok(())
    }

    /// sync a virtual keyboard with the manage sequence
    ///
    /// Mark a zwp_virtual_keyboard_v1 as synchronized with the
    /// river_window_manager_v1 manage sequence.
    ///
    /// Virtual keyboard events generated by the zwp_virtual_keyboard_v1.key and
    /// zwp_virtual_keyboard_v1.modifiers requests on the given virtual keyboard
    /// are queued and sent to the client with keyboard focus in a batch at the
    /// end of each manage sequence.
    ///
    /// Note that the capacity of the compositor's event queue is necessarily
    /// finite, though the compositor should choose large enough limits to allow
    /// any "reasonable" usage of this protocol.
    ///
    /// This request must be made before the first
    /// zwp_virtual_keyboard_v1.keymap request for the given virtual keyboard.
    ///
    /// This request only has an effect if the client is the active river window
    /// manager.
    ///
    /// This request is idempotent, subsequent requests for the same
    /// zwp_virtual_keyboard_v1 object have no effect.
    ///
    /// # Arguments
    ///
    /// - `virtual_keyboard`: virtual keyboard to sync
    #[inline]
    pub fn send_sync_keyboard(
        &self,
        virtual_keyboard: &Rc<ZwpVirtualKeyboardV1>,
    ) {
        let res = self.try_send_sync_keyboard(
            virtual_keyboard,
        );
        if let Err(e) = res {
            log_send("river_virtual_keyboard_manager_v1.sync_keyboard", &e);
        }
    }
}

/// A message handler for [`RiverVirtualKeyboardManagerV1`] proxies.
pub trait RiverVirtualKeyboardManagerV1Handler: Any {
    /// Event handler for wl_display.delete_id messages deleting the ID of this object.
    ///
    /// The default handler forwards the event to the client, if any.
    #[inline]
    fn delete_id(&mut self, slf: &Rc<RiverVirtualKeyboardManagerV1>) {
        slf.core.delete_id();
    }

    /// destroy the river_virtual_keyboard_v1 object
    ///
    /// This request indicates that the client will no longer use the
    /// river_virtual_keyboard_v1 object.
    #[inline]
    fn handle_destroy(
        &mut self,
        slf: &Rc<RiverVirtualKeyboardManagerV1>,
    ) {
        if !slf.core.forward_to_server.get() {
            return;
        }
        let res = slf.try_send_destroy(
        );
        if let Err(e) = res {
            log_forward("river_virtual_keyboard_manager_v1.destroy", &e);
        }
    }

    /// sync a virtual keyboard with the manage sequence
    ///
    /// Mark a zwp_virtual_keyboard_v1 as synchronized with the
    /// river_window_manager_v1 manage sequence.
    ///
    /// Virtual keyboard events generated by the zwp_virtual_keyboard_v1.key and
    /// zwp_virtual_keyboard_v1.modifiers requests on the given virtual keyboard
    /// are queued and sent to the client with keyboard focus in a batch at the
    /// end of each manage sequence.
    ///
    /// Note that the capacity of the compositor's event queue is necessarily
    /// finite, though the compositor should choose large enough limits to allow
    /// any "reasonable" usage of this protocol.
    ///
    /// This request must be made before the first
    /// zwp_virtual_keyboard_v1.keymap request for the given virtual keyboard.
    ///
    /// This request only has an effect if the client is the active river window
    /// manager.
    ///
    /// This request is idempotent, subsequent requests for the same
    /// zwp_virtual_keyboard_v1 object have no effect.
    ///
    /// # Arguments
    ///
    /// - `virtual_keyboard`: virtual keyboard to sync
    ///
    /// All borrowed proxies passed to this function are guaranteed to be
    /// immutable and non-null.
    #[inline]
    fn handle_sync_keyboard(
        &mut self,
        slf: &Rc<RiverVirtualKeyboardManagerV1>,
        virtual_keyboard: &Rc<ZwpVirtualKeyboardV1>,
    ) {
        if !slf.core.forward_to_server.get() {
            return;
        }
        let res = slf.try_send_sync_keyboard(
            virtual_keyboard,
        );
        if let Err(e) = res {
            log_forward("river_virtual_keyboard_manager_v1.sync_keyboard", &e);
        }
    }
}

impl ObjectPrivate for RiverVirtualKeyboardManagerV1 {
    fn new(state: &Rc<State>, version: u32) -> Rc<Self> {
        Rc::<Self>::new_cyclic(|slf| Self {
            core: ObjectCore::new(state, slf.clone(), ObjectInterface::RiverVirtualKeyboardManagerV1, version),
            handler: Default::default(),
        })
    }

    fn delete_id(self: Rc<Self>) -> Result<(), (ObjectError, Rc<dyn Object>)> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err((ObjectError(ObjectErrorKind::HandlerBorrowed), self));
        };
        if let Some(handler) = &mut *handler {
            handler.delete_id(&self);
        } else {
            self.core.delete_id();
        }
        Ok(())
    }

    fn handle_request(self: Rc<Self>, client: &Rc<Client>, msg: &[u32], fds: &mut VecDeque<Rc<OwnedFd>>) -> Result<(), ObjectError> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err(ObjectError(ObjectErrorKind::HandlerBorrowed));
        };
        let handler = &mut *handler;
        match msg[1] & 0xffff {
            0 => {
                if msg.len() != 2 {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 8)));
                }
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, client_id: u64, id: u32) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} -> river_virtual_keyboard_manager_v1#{}.destroy()\n", client_id, id);
                        state.log(args);
                    }
                    log(&self.core.state, client.endpoint.id, msg[0]);
                }
                self.core.handle_client_destroy();
                if let Some(handler) = handler {
                    (**handler).handle_destroy(&self);
                } else {
                    DefaultHandler.handle_destroy(&self);
                }
            }
            1 => {
                let [
                    arg0,
                ] = msg[2..] else {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 12)));
                };
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, client_id: u64, id: u32, arg0: u32) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} -> river_virtual_keyboard_manager_v1#{}.sync_keyboard(virtual_keyboard: zwp_virtual_keyboard_v1#{})\n", client_id, id, arg0);
                        state.log(args);
                    }
                    log(&self.core.state, client.endpoint.id, msg[0], arg0);
                }
                let arg0_id = arg0;
                let Some(arg0) = client.endpoint.lookup(arg0_id) else {
                    return Err(ObjectError(ObjectErrorKind::NoClientObject(client.endpoint.id, arg0_id)));
                };
                let Ok(arg0) = (arg0 as Rc<dyn Any>).downcast::<ZwpVirtualKeyboardV1>() else {
                    let o = client.endpoint.lookup(arg0_id).unwrap();
                    return Err(ObjectError(ObjectErrorKind::WrongObjectType("virtual_keyboard", o.core().interface, ObjectInterface::ZwpVirtualKeyboardV1)));
                };
                let arg0 = &arg0;
                if let Some(handler) = handler {
                    (**handler).handle_sync_keyboard(&self, arg0);
                } else {
                    DefaultHandler.handle_sync_keyboard(&self, arg0);
                }
            }
            n => {
                let _ = client;
                let _ = msg;
                let _ = fds;
                let _ = handler;
                return Err(ObjectError(ObjectErrorKind::UnknownMessageId(n)));
            }
        }
        Ok(())
    }

    fn handle_event(self: Rc<Self>, server: &Endpoint, msg: &[u32], fds: &mut VecDeque<Rc<OwnedFd>>) -> Result<(), ObjectError> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err(ObjectError(ObjectErrorKind::HandlerBorrowed));
        };
        let handler = &mut *handler;
        match msg[1] & 0xffff {
            n => {
                let _ = server;
                let _ = msg;
                let _ = fds;
                let _ = handler;
                return Err(ObjectError(ObjectErrorKind::UnknownMessageId(n)));
            }
        }
    }

    fn get_request_name(&self, id: u32) -> Option<&'static str> {
        let name = match id {
            0 => "destroy",
            1 => "sync_keyboard",
            _ => return None,
        };
        Some(name)
    }

    fn get_event_name(&self, id: u32) -> Option<&'static str> {
        let _ = id;
        None
    }

    fn create_zombie(&self) -> Rc<dyn Object> {
        let slf = Self::new(&self.core.state, self.core.version);
        slf.core.make_zombie();
        slf
    }
}

impl Object for RiverVirtualKeyboardManagerV1 {
    fn core(&self) -> &ObjectCore {
        &self.core
    }

    fn unset_handler(&self) {
        self.handler.set(None);
    }

    fn get_handler_any_ref(&self) -> Result<HandlerRef<'_, dyn Any>, HandlerAccessError> {
        let borrowed = self.handler.try_borrow().ok_or(HandlerAccessError::AlreadyBorrowed)?;
        if borrowed.is_none() {
            return Err(HandlerAccessError::NoHandler);
        }
        Ok(HandlerRef::map(borrowed, |handler| &**handler.as_ref().unwrap() as &dyn Any))
    }

    fn get_handler_any_mut(&self) -> Result<HandlerMut<'_, dyn Any>, HandlerAccessError> {
        let borrowed = self.handler.try_borrow_mut().ok_or(HandlerAccessError::AlreadyBorrowed)?;
        if borrowed.is_none() {
            return Err(HandlerAccessError::NoHandler);
        }
        Ok(HandlerMut::map(borrowed, |handler| &mut **handler.as_mut().unwrap() as &mut dyn Any))
    }
}

impl RiverVirtualKeyboardManagerV1 {
    /// Since when the error.keymap_already_set enum variant is available.
    pub const ENM__ERROR_KEYMAP_ALREADY_SET__SINCE: u32 = 1;
}

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct RiverVirtualKeyboardManagerV1Error(pub u32);

impl RiverVirtualKeyboardManagerV1Error {
    /// virtual keyboard must be synced before setting keymap
    pub const KEYMAP_ALREADY_SET: Self = Self(0);
}

impl Debug for RiverVirtualKeyboardManagerV1Error {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let name = match *self {
            Self::KEYMAP_ALREADY_SET => "KEYMAP_ALREADY_SET",
            _ => return Debug::fmt(&self.0, f),
        };
        f.write_str(name)
    }
}
