//! app id resolver
//!
//! The compositor sends identify_request with a unique request_id and a pidfd.
//! The client must answer exactly once via respond(request_id, app_id). If
//! resolution fails respond with an empty string.

use crate::protocol_helpers::prelude::*;
use super::super::all_types::*;

/// A treeland_app_id_resolver_v1 object.
///
/// See the documentation of [the module][self] for the interface description.
pub struct TreelandAppIdResolverV1 {
    core: ObjectCore,
    handler: HandlerHolder<dyn TreelandAppIdResolverV1Handler>,
}

struct DefaultHandler;

impl TreelandAppIdResolverV1Handler for DefaultHandler { }

impl ConcreteObject for TreelandAppIdResolverV1 {
    const XML_VERSION: u32 = 1;
    const INTERFACE: ObjectInterface = ObjectInterface::TreelandAppIdResolverV1;
    const INTERFACE_NAME: &str = "treeland_app_id_resolver_v1";
}

impl TreelandAppIdResolverV1 {
    /// Sets a new handler.
    pub fn set_handler(&self, handler: impl TreelandAppIdResolverV1Handler) {
        self.set_boxed_handler(Box::new(handler));
    }

    /// Sets a new, already boxed handler.
    pub fn set_boxed_handler(&self, handler: Box<dyn TreelandAppIdResolverV1Handler>) {
        if self.core.state.destroyed.get() {
            return;
        }
        self.handler.set(Some(handler));
    }
}

impl Debug for TreelandAppIdResolverV1 {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TreelandAppIdResolverV1")
            .field("server_obj_id", &self.core.server_obj_id.get())
            .field("client_id", &self.core.client_id.get())
            .field("client_obj_id", &self.core.client_obj_id.get())
            .finish()
    }
}

impl TreelandAppIdResolverV1 {
    /// Since when the identify_request message is available.
    pub const MSG__IDENTIFY_REQUEST__SINCE: u32 = 1;

    /// ask client to resolve pidfd to application id
    ///
    /// # Arguments
    ///
    /// - `request_id`: monotonic id generated by compositor
    /// - `pidfd`: pidfd referencing the target process
    #[inline]
    pub fn try_send_identify_request(
        &self,
        request_id: u32,
        pidfd: &Rc<OwnedFd>,
    ) -> Result<(), ObjectError> {
        let (
            arg0,
            arg1,
        ) = (
            request_id,
            pidfd,
        );
        let core = self.core();
        let client_ref = core.client.borrow();
        let Some(client) = &*client_ref else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoClient));
        };
        let id = core.client_obj_id.get().unwrap_or(0);
        if self.core.state.log {
            #[cold]
            fn log(state: &State, client_id: u64, id: u32, arg0: u32, arg1: i32) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} <= treeland_app_id_resolver_v1#{}.identify_request(request_id: {}, pidfd: {})\n", client_id, id, arg0, arg1);
                state.log(args);
            }
            log(&self.core.state, client.endpoint.id, id, arg0, arg1.as_raw_fd());
        }
        let endpoint = &client.endpoint;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, Some(client));
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.fds.push_back(arg1.clone());
        fmt.words([
            id,
            0,
            arg0,
        ]);
        Ok(())
    }

    /// ask client to resolve pidfd to application id
    ///
    /// # Arguments
    ///
    /// - `request_id`: monotonic id generated by compositor
    /// - `pidfd`: pidfd referencing the target process
    #[inline]
    pub fn send_identify_request(
        &self,
        request_id: u32,
        pidfd: &Rc<OwnedFd>,
    ) {
        let res = self.try_send_identify_request(
            request_id,
            pidfd,
        );
        if let Err(e) = res {
            log_send("treeland_app_id_resolver_v1.identify_request", &e);
        }
    }

    /// Since when the respond message is available.
    pub const MSG__RESPOND__SINCE: u32 = 1;

    /// respond with app id and sandbox_engine_name (empty app_id on failure)
    ///
    /// Respond to an identify_request. The sandbox_engine_name must be provided and
    /// matches the context in which the process is running (container, sandbox, etc).
    /// If resolution fails, respond with an empty app_id.
    ///
    /// # Arguments
    ///
    /// - `request_id`:
    /// - `app_id`:
    /// - `sandbox_engine_name`: the sandbox engine / security context name (required, non-empty)
    #[inline]
    pub fn try_send_respond(
        &self,
        request_id: u32,
        app_id: &str,
        sandbox_engine_name: &str,
    ) -> Result<(), ObjectError> {
        let (
            arg0,
            arg1,
            arg2,
        ) = (
            request_id,
            app_id,
            sandbox_engine_name,
        );
        let core = self.core();
        let Some(id) = core.server_obj_id.get() else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoServerId));
        };
        if self.core.state.log {
            #[cold]
            fn log(state: &State, id: u32, arg0: u32, arg1: &str, arg2: &str) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      <= treeland_app_id_resolver_v1#{}.respond(request_id: {}, app_id: {:?}, sandbox_engine_name: {:?})\n", id, arg0, arg1, arg2);
                state.log(args);
            }
            log(&self.core.state, id, arg0, arg1, arg2);
        }
        let endpoint = &self.core.state.server;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, None);
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            0,
            arg0,
        ]);
        fmt.string(arg1);
        fmt.string(arg2);
        Ok(())
    }

    /// respond with app id and sandbox_engine_name (empty app_id on failure)
    ///
    /// Respond to an identify_request. The sandbox_engine_name must be provided and
    /// matches the context in which the process is running (container, sandbox, etc).
    /// If resolution fails, respond with an empty app_id.
    ///
    /// # Arguments
    ///
    /// - `request_id`:
    /// - `app_id`:
    /// - `sandbox_engine_name`: the sandbox engine / security context name (required, non-empty)
    #[inline]
    pub fn send_respond(
        &self,
        request_id: u32,
        app_id: &str,
        sandbox_engine_name: &str,
    ) {
        let res = self.try_send_respond(
            request_id,
            app_id,
            sandbox_engine_name,
        );
        if let Err(e) = res {
            log_send("treeland_app_id_resolver_v1.respond", &e);
        }
    }

    /// Since when the destroy message is available.
    pub const MSG__DESTROY__SINCE: u32 = 1;

    /// destroy resolver
    #[inline]
    pub fn try_send_destroy(
        &self,
    ) -> Result<(), ObjectError> {
        let core = self.core();
        let Some(id) = core.server_obj_id.get() else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoServerId));
        };
        if self.core.state.log {
            #[cold]
            fn log(state: &State, id: u32) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      <= treeland_app_id_resolver_v1#{}.destroy()\n", id);
                state.log(args);
            }
            log(&self.core.state, id);
        }
        let endpoint = &self.core.state.server;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, None);
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            1,
        ]);
        self.core.handle_server_destroy();
        Ok(())
    }

    /// destroy resolver
    #[inline]
    pub fn send_destroy(
        &self,
    ) {
        let res = self.try_send_destroy(
        );
        if let Err(e) = res {
            log_send("treeland_app_id_resolver_v1.destroy", &e);
        }
    }
}

/// A message handler for [`TreelandAppIdResolverV1`] proxies.
pub trait TreelandAppIdResolverV1Handler: Any {
    /// Event handler for wl_display.delete_id messages deleting the ID of this object.
    ///
    /// The default handler forwards the event to the client, if any.
    #[inline]
    fn delete_id(&mut self, slf: &Rc<TreelandAppIdResolverV1>) {
        slf.core.delete_id();
    }

    /// ask client to resolve pidfd to application id
    ///
    /// # Arguments
    ///
    /// - `request_id`: monotonic id generated by compositor
    /// - `pidfd`: pidfd referencing the target process
    #[inline]
    fn handle_identify_request(
        &mut self,
        slf: &Rc<TreelandAppIdResolverV1>,
        request_id: u32,
        pidfd: &Rc<OwnedFd>,
    ) {
        if !slf.core.forward_to_client.get() {
            return;
        }
        let res = slf.try_send_identify_request(
            request_id,
            pidfd,
        );
        if let Err(e) = res {
            log_forward("treeland_app_id_resolver_v1.identify_request", &e);
        }
    }

    /// respond with app id and sandbox_engine_name (empty app_id on failure)
    ///
    /// Respond to an identify_request. The sandbox_engine_name must be provided and
    /// matches the context in which the process is running (container, sandbox, etc).
    /// If resolution fails, respond with an empty app_id.
    ///
    /// # Arguments
    ///
    /// - `request_id`:
    /// - `app_id`:
    /// - `sandbox_engine_name`: the sandbox engine / security context name (required, non-empty)
    #[inline]
    fn handle_respond(
        &mut self,
        slf: &Rc<TreelandAppIdResolverV1>,
        request_id: u32,
        app_id: &str,
        sandbox_engine_name: &str,
    ) {
        if !slf.core.forward_to_server.get() {
            return;
        }
        let res = slf.try_send_respond(
            request_id,
            app_id,
            sandbox_engine_name,
        );
        if let Err(e) = res {
            log_forward("treeland_app_id_resolver_v1.respond", &e);
        }
    }

    /// destroy resolver
    #[inline]
    fn handle_destroy(
        &mut self,
        slf: &Rc<TreelandAppIdResolverV1>,
    ) {
        if !slf.core.forward_to_server.get() {
            return;
        }
        let res = slf.try_send_destroy(
        );
        if let Err(e) = res {
            log_forward("treeland_app_id_resolver_v1.destroy", &e);
        }
    }
}

impl ObjectPrivate for TreelandAppIdResolverV1 {
    fn new(state: &Rc<State>, version: u32) -> Rc<Self> {
        Rc::<Self>::new_cyclic(|slf| Self {
            core: ObjectCore::new(state, slf.clone(), ObjectInterface::TreelandAppIdResolverV1, version),
            handler: Default::default(),
        })
    }

    fn delete_id(self: Rc<Self>) -> Result<(), (ObjectError, Rc<dyn Object>)> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err((ObjectError(ObjectErrorKind::HandlerBorrowed), self));
        };
        if let Some(handler) = &mut *handler {
            handler.delete_id(&self);
        } else {
            self.core.delete_id();
        }
        Ok(())
    }

    fn handle_request(self: Rc<Self>, client: &Rc<Client>, msg: &[u32], fds: &mut VecDeque<Rc<OwnedFd>>) -> Result<(), ObjectError> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err(ObjectError(ObjectErrorKind::HandlerBorrowed));
        };
        let handler = &mut *handler;
        match msg[1] & 0xffff {
            0 => {
                let mut offset = 2;
                let Some(&arg0) = msg.get(offset) else {
                    return Err(ObjectError(ObjectErrorKind::MissingArgument("request_id")));
                };
                offset += 1;
                let arg1 = {
                    let Some(&len) = msg.get(offset) else {
                        return Err(ObjectError(ObjectErrorKind::MissingArgument("app_id")));
                    };
                    offset += 1;
                    let len = len as usize;
                    let words = ((len as u64 + 3) / 4) as usize;
                    if offset + words > msg.len() {
                        return Err(ObjectError(ObjectErrorKind::MissingArgument("app_id")));
                    }
                    let start = offset;
                    offset += words;
                    let bytes = &uapi::as_bytes(&msg[start..])[..len];
                    if bytes.is_empty() {
                        return Err(ObjectError(ObjectErrorKind::NullString("app_id")));
                    } else {
                        let Ok(s) = str::from_utf8(&bytes[..len-1]) else {
                            return Err(ObjectError(ObjectErrorKind::NonUtf8("app_id")));
                        };
                        s
                    }
                };
                let arg2 = {
                    let Some(&len) = msg.get(offset) else {
                        return Err(ObjectError(ObjectErrorKind::MissingArgument("sandbox_engine_name")));
                    };
                    offset += 1;
                    let len = len as usize;
                    let words = ((len as u64 + 3) / 4) as usize;
                    if offset + words > msg.len() {
                        return Err(ObjectError(ObjectErrorKind::MissingArgument("sandbox_engine_name")));
                    }
                    let start = offset;
                    offset += words;
                    let bytes = &uapi::as_bytes(&msg[start..])[..len];
                    if bytes.is_empty() {
                        return Err(ObjectError(ObjectErrorKind::NullString("sandbox_engine_name")));
                    } else {
                        let Ok(s) = str::from_utf8(&bytes[..len-1]) else {
                            return Err(ObjectError(ObjectErrorKind::NonUtf8("sandbox_engine_name")));
                        };
                        s
                    }
                };
                if offset != msg.len() {
                    return Err(ObjectError(ObjectErrorKind::TrailingBytes));
                }
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, client_id: u64, id: u32, arg0: u32, arg1: &str, arg2: &str) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} -> treeland_app_id_resolver_v1#{}.respond(request_id: {}, app_id: {:?}, sandbox_engine_name: {:?})\n", client_id, id, arg0, arg1, arg2);
                        state.log(args);
                    }
                    log(&self.core.state, client.endpoint.id, msg[0], arg0, arg1, arg2);
                }
                if let Some(handler) = handler {
                    (**handler).handle_respond(&self, arg0, arg1, arg2);
                } else {
                    DefaultHandler.handle_respond(&self, arg0, arg1, arg2);
                }
            }
            1 => {
                if msg.len() != 2 {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 8)));
                }
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, client_id: u64, id: u32) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} -> treeland_app_id_resolver_v1#{}.destroy()\n", client_id, id);
                        state.log(args);
                    }
                    log(&self.core.state, client.endpoint.id, msg[0]);
                }
                self.core.handle_client_destroy();
                if let Some(handler) = handler {
                    (**handler).handle_destroy(&self);
                } else {
                    DefaultHandler.handle_destroy(&self);
                }
            }
            n => {
                let _ = client;
                let _ = msg;
                let _ = fds;
                let _ = handler;
                return Err(ObjectError(ObjectErrorKind::UnknownMessageId(n)));
            }
        }
        Ok(())
    }

    fn handle_event(self: Rc<Self>, msg: &[u32], fds: &mut VecDeque<Rc<OwnedFd>>) -> Result<(), ObjectError> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err(ObjectError(ObjectErrorKind::HandlerBorrowed));
        };
        let handler = &mut *handler;
        match msg[1] & 0xffff {
            0 => {
                let [
                    arg0,
                ] = msg[2..] else {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 12)));
                };
                let Some(arg1) = fds.pop_front() else {
                    return Err(ObjectError(ObjectErrorKind::MissingFd("pidfd")));
                };
                let arg1 = &arg1;
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, id: u32, arg0: u32, arg1: i32) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      -> treeland_app_id_resolver_v1#{}.identify_request(request_id: {}, pidfd: {})\n", id, arg0, arg1);
                        state.log(args);
                    }
                    log(&self.core.state, msg[0], arg0, arg1.as_raw_fd());
                }
                if let Some(handler) = handler {
                    (**handler).handle_identify_request(&self, arg0, arg1);
                } else {
                    DefaultHandler.handle_identify_request(&self, arg0, arg1);
                }
            }
            n => {
                let _ = msg;
                let _ = fds;
                let _ = handler;
                return Err(ObjectError(ObjectErrorKind::UnknownMessageId(n)));
            }
        }
        Ok(())
    }

    fn get_request_name(&self, id: u32) -> Option<&'static str> {
        let name = match id {
            0 => "respond",
            1 => "destroy",
            _ => return None,
        };
        Some(name)
    }

    fn get_event_name(&self, id: u32) -> Option<&'static str> {
        let name = match id {
            0 => "identify_request",
            _ => return None,
        };
        Some(name)
    }
}

impl Object for TreelandAppIdResolverV1 {
    fn core(&self) -> &ObjectCore {
        &self.core
    }

    fn unset_handler(&self) {
        self.handler.set(None);
    }

    fn get_handler_any_ref(&self) -> Result<HandlerRef<'_, dyn Any>, HandlerAccessError> {
        let borrowed = self.handler.try_borrow().ok_or(HandlerAccessError::AlreadyBorrowed)?;
        if borrowed.is_none() {
            return Err(HandlerAccessError::NoHandler);
        }
        Ok(HandlerRef::map(borrowed, |handler| &**handler.as_ref().unwrap() as &dyn Any))
    }

    fn get_handler_any_mut(&self) -> Result<HandlerMut<'_, dyn Any>, HandlerAccessError> {
        let borrowed = self.handler.try_borrow_mut().ok_or(HandlerAccessError::AlreadyBorrowed)?;
        if borrowed.is_none() {
            return Err(HandlerAccessError::NoHandler);
        }
        Ok(HandlerMut::map(borrowed, |handler| &mut **handler.as_mut().unwrap() as &mut dyn Any))
    }
}

